name: Publish Package

on:
  push:
    branches:
      - develop
      - feature-3-keycloak-automatic-deployment

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Resolve base version
      run: |
        echo "BASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout|cut -d'-' -f1)" >> $GITHUB_ENV

    - name: Bump version to develop version
      run: mvn versions:set -DnewVersion=${{ env.BASE_VERSION }}-develop

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Bump to next snapshot
      run: mvn versions:set -DnewVersion=${{ env.BASE_VERSION }} && mvn versions:set -DnextSnapshot=true

    - name: Commit changes
      run: |
        git add pom.xml
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit --allow-empty -m "Bumped version"

    - name: Push version changes to develop
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: Install staging Keycloak
      uses: peter-evans/repository-dispatch@v3
      with:
        repository: Metatavu/vp-kuljetus-transport-management-keycloak
        event-type: update-staging
        token: ${{ secrets.KEYCLOAK_UPDATE_PAT }}

    
